In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("regions_data.csv")

In [5]:
data

   Year Region 1 Region 2 Region 3 Region 4 Region 5
0  2016        N        N        N        N        N
1  2017        Y        N        N        N        N
2  2018        Y        N        N        N        N
3  2019        Y        N        N        N        N
4  2020        Y        N        Y        N        N
5  2021        Y        Y        Y        N        N
6  2022        Y        Y        Y        Y        N
7  2023        Y        Y        Y        Y        N
8  2024        Y        Y        Y        Y        N
9  2025        Y        Y        Y        Y        N

In [7]:
for index, row in data.iterrows():
    year = row["Year"]  # Extract the year
    region_data = {col: row[col] for col in data.columns if col != "Year"}  # Extract region data (Y/N)
    
    # Print the extracted data
    print(f"Year: {year}")
    for region, value in region_data.items():
        print(f"  {region}: {value}")

Year: 2016
  Region 1: N
  Region 2: N
  Region 3: N
  Region 4: N
  Region 5: N
Year: 2017
  Region 1: Y
  Region 2: N
  Region 3: N
  Region 4: N
  Region 5: N
Year: 2018
  Region 1: Y
  Region 2: N
  Region 3: N
  Region 4: N
  Region 5: N
Year: 2019
  Region 1: Y
  Region 2: N
  Region 3: N
  Region 4: N
  Region 5: N
Year: 2020
  Region 1: Y
  Region 2: N
  Region 3: Y
  Region 4: N
  Region 5: N
Year: 2021
  Region 1: Y
  Region 2: Y
  Region 3: Y
  Region 4: N
  Region 5: N
Year: 2022
  Region 1: Y
  Region 2: Y
  Region 3: Y
  Region 4: Y
  Region 5: N
Year: 2023
  Region 1: Y
  Region 2: Y
  Region 3: Y
  Region 4: Y
  Region 5: N
Year: 2024
  Region 1: Y
  Region 2: Y
  Region 3: Y
  Region 4: Y
  Region 5: N
Year: 2025
  Region 1: Y
  Region 2: Y
  Region 3: Y
  Region 4: Y
  Region 5: N